# Generated by Django 5.2.6 on 2025-10-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Playlist or video title', max_length=200)),
                ('youtube_id', models.CharField(help_text='YouTube playlist ID or video ID', max_length=100)),
                ('content_type', models.CharField(choices=[('BREATHING', 'Breathing Sessions'), ('YOGA', 'Yoga for Relaxation'), ('ASMR', 'ASMR Videos'), ('CHILL_MUSIC', 'Chill Music'), ('STUDY_MUSIC', 'Study Music'), ('STUDY_TIPS', 'Study Tips'), ('MOTIVATION', 'Motivational Videos')], max_length=20)),
                ('category', models.CharField(choices=[('RELAX', 'Relaxation'), ('STUDY', 'Study')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_playlist', models.BooleanField(default=True, help_text="True if it's a playlist, False if it's a single video")),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'content_type', 'order'],
            },
        ),
    ]
