# Generated by Django 4.2.25 on 2026-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0002_mediaplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, help_text='Upload an MP3/OGG/WAV file', null=True, upload_to='study_music/')),
                ('audio_url', models.URLField(blank=True, help_text='Or paste a direct audio URL (MP3/OGG). Leave blank if uploading a file.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Background Music Track',
                'verbose_name_plural': 'Background Music Tracks',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(help_text='Paste the full YouTube URL (watch?v= or youtu.be/)')),
                ('category', models.CharField(choices=[('tips', 'Study Tips'), ('motivation', 'Motivational')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Study Video',
                'verbose_name_plural': 'Study Videos',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
