# Generated by Django 4.2.25 on 2026-04-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haven', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorbooking',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The student who made this booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
